import {
  gameContent,
  immunityCodeAnnouncementExtension,
  requalifyCodeAnnouncementExtension,
  barredSwapAnnouncementExtension,
  barredCandidateTwistVoteExtension,
} from './content'
import audioManifestData from './audioManifest.json'
import { ExecutiveDecisionType, StatusTypes } from '../types/types'

export const DEFAULT_HOST_PAUSE_MS = 100

// Every non-rules status's hostMessage is a flat string[] where each entry is both the
// narration script and (indirectly) the on-screen caption. Rules is denser: each entry
// carries separate `audio` (what Lucin speaks) and `display` (short caption) text, and
// heading entries (e.g. "Phase 1: Campaign") nest their body lines underneath via
// `content`, instead of the heading and its body being separate top-level entries.
interface RawRulesSubLine {
  audio: string
  display: string
}

interface RawRulesTopLine {
  audio: string
  display: string
  // null for a standalone line; an array for a heading whose body lines are nested here.
  content: RawRulesSubLine[] | null
}

// The normalized shape every consumer works with after flattening — audio text to speak,
// display text to show on screen, and isHeading derived structurally (from whether the
// raw entry had nested content), not sniffed from wording like "starts with Phase".
export interface FlatHostMessageLine {
  audio: string
  display: string
  isHeading: boolean
}

export type HostMessageEntry = string | FlatHostMessageLine

export function getHostMessageAudioText(entry: HostMessageEntry): string {
  return typeof entry === 'string' ? entry : entry.audio
}

export function getHostMessageDisplayText(entry: HostMessageEntry): string {
  return typeof entry === 'string' ? entry : entry.display
}

export function isHostMessageHeading(entry: HostMessageEntry): boolean {
  return typeof entry === 'string' ? false : entry.isHeading
}

// Flattens a (possibly nested) hostMessage array into one ordered list of narration
// lines. Preserves original line order (heading, then its nested lines, in sequence).
// Plain string[] statuses pass through as non-heading lines with audio === display.
export function flattenHostMessages(entries: unknown): FlatHostMessageLine[] {
  if (!Array.isArray(entries)) return []

  const result: FlatHostMessageLine[] = []
  for (const entry of entries as (string | RawRulesTopLine)[]) {
    if (typeof entry === 'string') {
      result.push({ audio: entry, display: entry, isHeading: false })
      continue
    }
    const children = Array.isArray(entry.content) ? entry.content : null
    result.push({ audio: entry.audio, display: entry.display, isHeading: Boolean(children?.length) })
    if (children) {
      for (const child of children) {
        result.push({ audio: child.audio, display: child.display, isHeading: false })
      }
    }
  }
  return result
}

export interface HostNarrationSegment {
  id: string
  status: StatusTypes
  index: number
  text: string
  audioObjectKey: string | null
  audioUrl: string | null
  pauseAfterMs: number
  hasDynamicTokens: boolean
}

// v2/{hash}.mp3 — content-addressed by exact spoken text (see scripts/generate-audio.ts),
// not by status/position, so editing/reordering/adding lines never invalidates existing
// audio. The manifest (text -> object key) is generated by that script and committed here;
// this is a plain JSON import (not a runtime hash computation), so key resolution works
// identically server-side and in the browser — the host page calls this client-side.
const TEXT_TO_AUDIO_KEY: Record<string, string> = Object.fromEntries(
  Object.entries(audioManifestData as Record<string, string>).map(([key, text]) => [text.trim(), key])
)

function buildAudioObjectKey(text: string): string | null {
  return TEXT_TO_AUDIO_KEY[text.trim()] ?? null
}

function buildAudioUrl(audioObjectKey: string | null): string | null {
  if (!audioObjectKey) return null
  const base = process.env.NEXT_PUBLIC_AUDIO_OBJECT_BASE_URL?.trim()
  if (!base) return null
  const normalized = base.endsWith('/') ? base.slice(0, -1) : base
  return `${normalized}/${audioObjectKey}`
}

// For narration sequenced outside the generic per-status system (e.g. the 'intro'
// sequence, which plays introductionAnnouncementExtension directly rather than through
// getHostNarrationSegment) — resolves a line of text straight to its v2 audio URL.
export function getAudioUrlForText(text: string): string | null {
  return buildAudioUrl(buildAudioObjectKey(text))
}

function getExecutiveDecisionAnnouncementExtension(executiveDecision?: ExecutiveDecisionType): unknown[] {
  if (executiveDecision === 'immunity_code') return immunityCodeAnnouncementExtension
  if (executiveDecision === 'requalify_code') return requalifyCodeAnnouncementExtension
  if (executiveDecision === 'barred_swap_chance') return barredSwapAnnouncementExtension
  return []
}

// Combine raw entries (base status + any executive-decision extension) BEFORE flattening,
// so a single flattenHostMessages() pass resolves both — every entry (base or extension)
// goes through the exact same {id,audio,display,content?} handling either way.
function getEffectiveHostMessages(status: StatusTypes, executiveDecision?: ExecutiveDecisionType, isTwistRound?: boolean): string[] {
  const baseEntries = gameContent[status]?.hostMessage
  const rawEntries: unknown[] = Array.isArray(baseEntries) ? [...baseEntries] : []

  if (status === 'announcement') {
    rawEntries.push(...getExecutiveDecisionAnnouncementExtension(executiveDecision))
  }

  // One-time barred-candidate-twist round: the normal vote-phase narration plays first,
  // then these 4 lines are appended — only for the specific round the twist fires in (see
  // game.activeTwistRound in types/types.ts).
  if (status === 'vote' && isTwistRound) {
    rawEntries.push(...barredCandidateTwistVoteExtension)
  }

  return flattenHostMessages(rawEntries).map(line => line.audio)
}

function logExecutiveDecisionAudio(event: string, data: Record<string, unknown>) {
  console.log('[HostNarration][ExecutiveAudio]', event, data)
}

function asHostMessages(value: unknown): string[] {
  return flattenHostMessages(value).map(line => line.audio)
}

// A line that is purely a {TOKEN} placeholder (e.g. "{LEADER_NAME}") has no real text to
// speak — the host page never plays audio for these (see hasDynamicTokens handling in
// pages/host/[code].tsx) regardless of whether a URL exists, so nothing should ever
// generate/upload audio for one either.
export function isDynamicTokenLine(text: string): boolean {
  const trimmed = text.trim()
  return /^\{[^{}]+\}$/.test(trimmed)
}

// {TIME} is excluded from the dramatic-pause treatment below: unlike {LEADER_NAME}/
// {WINNER_NAME}/etc. (one-time suspenseful reveals worth pausing before), {TIME} is a
// continuously-updating countdown, not a reveal — pausing 8s before showing the line
// after it (e.g. "Time until next election.") just left that context text hidden for no
// reason while the clock was already ticking.
function isDramaticPauseToken(text: string): boolean {
  return isDynamicTokenLine(text) && text.trim() !== '{TIME}'
}

function computePauseMs(status: StatusTypes, index: number, hostMessages: string[], id: string): number {
  const currentText = hostMessages[index] ?? ''
  const nextText = hostMessages[index + 1] ?? ''
  const isCurrentDynamicToken = isDramaticPauseToken(currentText)
  const isNextDynamicToken = isDramaticPauseToken(nextText)

  // Add dramatic pause after dynamic token lines and before the next dynamic token line.
  if (isCurrentDynamicToken || isNextDynamicToken) {
    return 8000
  }

  return DEFAULT_HOST_PAUSE_MS
}

export function getHostNarrationSegments(status: StatusTypes, executiveDecision?: ExecutiveDecisionType, isTwistRound?: boolean): HostNarrationSegment[] {
  const hostMessages = getEffectiveHostMessages(status, executiveDecision, isTwistRound)

  return hostMessages.map((text, index) => {
    const id = `${status}.hostMessage.${index}`
    const audioObjectKey = buildAudioObjectKey(text)
    return {
      id,
      status,
      index,
      text,
      audioObjectKey,
      audioUrl: buildAudioUrl(audioObjectKey),
      pauseAfterMs: computePauseMs(status, index, hostMessages, id),
      hasDynamicTokens: text.includes('{') && text.includes('}')
    }
  })
}

export function getHostNarrationSegment(status: StatusTypes, index: number, executiveDecision?: ExecutiveDecisionType, isTwistRound?: boolean): HostNarrationSegment | null {
  const segments = getHostNarrationSegments(status, executiveDecision, isTwistRound)
  const segment = segments[index] ?? null

  if (executiveDecision && (status === 'decision' || status === 'announcement')) {
    logExecutiveDecisionAudio('segment.lookup', {
      status,
      executiveDecision,
      index,
      found: Boolean(segment),
      audioObjectKey: segment?.audioObjectKey ?? null,
      audioUrl: segment?.audioUrl ?? null,
      hasDynamicTokens: segment?.hasDynamicTokens ?? null,
      totalSegments: segments.length,
    })
  }

  return segment
}

export function getHostNarrationManifest(): Record<StatusTypes, HostNarrationSegment[]> {
  return {
    join: getHostNarrationSegments('join'),
    // 'intro' has no gameContent.intro.hostMessage entry — its narration comes from
    // introductionAnnouncementExtension and is sequenced directly by the host page's own
    // intro-sequence effect, not through the generic per-status narration segment system.
    intro: [],
    rules: getHostNarrationSegments('rules'),
    campaign: getHostNarrationSegments('campaign'),
    vote: getHostNarrationSegments('vote'),
    results: getHostNarrationSegments('results'),
    decision: getHostNarrationSegments('decision'),
    announcement: getHostNarrationSegments('announcement'),
    final: getHostNarrationSegments('final'),
  }
}
