export interface Player {
  id: string // UUID
  name: string
  votes: number
  leader: boolean
  isQualified: boolean // Can't gain voting points
  immuneFromBarInRound?: number // Round index where this player cannot be barred
  roundsBarred: number // Track how many rounds barred (for special privileges)
  isAdmin: boolean
  hasVoted: boolean // Track if player has voted in current round
  isConnected: boolean // Track if player is currently connected
}

export interface GameRound {
  roundNumber: number
  leader: string // Player ID
  barred: string[] // Array of barred player IDs
  votes: Record<string, string[]> // { voterId: [candidateId, candidateId, ...] } ranked ballots for the round
  roundStartTime: number // timestamp
}

export type StatusTypes = 'join' | 'intro' | 'rules' | 'campaign' | 'vote' | 'results' | 'decision' | 'announcement' | 'final'

// Player-facing phase (Rule of Three): campaign / election / executive / final
export type PhaseTypes = 'campaign' | 'election' | 'executive' | 'final'

// 'opt_out' is not leader-facing (never shown as a menu option) — it is the internal
// fallback value auto-submitted by the player client when qualified players <= 3 (see
// handleBarSubmit in LeaderDecisionPanel.tsx), representing "no executive decision this
// round". The three leader-facing decisions:
//  - immunity_code: leader generates a 4-letter code redeemable for immunity next cycle.
//  - requalify_code: leader generates a 4-letter code redeemable to requalify a barred player.
//  - barred_swap_chance: leader picks an already-barred player to get a 25s window (during
//    the announcement reveal) to bar a qualified player in their place and become qualified.
export type ExecutiveDecisionType = 'immunity_code' | 'requalify_code' | 'barred_swap_chance' | 'opt_out'

export type ActiveCodeType = 'immunity' | 'requalify'

// A single-use, round-scoped 4-letter redemption code generated by immunity_code /
// requalify_code. Valid only during the campaign phase of `validForRound` — cleared
// unconditionally when that campaign cycle ends (campaign -> vote), whether redeemed or
// not. `code` must never be broadcast to the host or to any player other than `ownerId`
// (see sanitizeGameForHost / buildPlayerProjection in server/gameStore.ts).
export interface ActiveRoundCode {
  code: string
  type: ActiveCodeType
  ownerId: string // player id of the leader who generated this code; cannot redeem their own code
  validForRound: number // matches game.currentRound during the campaign phase this code is valid for
}

export type SwapWindowStatus = 'pending' | 'active' | 'resolved' | 'expired'

// Per-round state for the barred_swap_chance decision. `barredPlayerId` identifies which
// already-barred player the leader gave a redemption chance to — this identity is only
// narrated (revealed) once the host's announcement sequence reaches that line, but is
// otherwise safe to include in the host payload (it is not a "which player is on the
// ballot" leak the way barring is, since that player was already publicly barred in a
// prior round). `status` starts 'pending' at decision-submit time, becomes 'active' (with
// a server-set `deadline`) when the host narration reaches the pause point, then either
// 'resolved' (the barred player submitted a swap target in time) or 'expired' (25s elapsed
// with no submission).
export interface SwapWindow {
  barredPlayerId: string
  status: SwapWindowStatus
  deadline?: number // epoch ms; set when status becomes 'active'
  resultQualifiedTargetId?: string // the player barred in exchange, once resolved
}

export interface Game {
  id: string // UUID
  code: string
  started: boolean
  status: StatusTypes
  cycleTime: number // seconds between elections (set by host)
  players: Player[]
  rounds: GameRound[]
  currentRound: number
  electionCycleStartTime: number // timestamp for countdown
  winner?: string | undefined; // Player ID of winner
  createdAt: number
  // Executive decision fields (set after leader submits decision)
  executiveDecision?: ExecutiveDecisionType
  // Active immunity_code / requalify_code redemption code (see ActiveRoundCode). Survives
  // the announcement -> campaign round reset on purpose (it becomes redeemable during that
  // very campaign phase) and is instead cleared at campaign -> vote.
  activeCode?: ActiveRoundCode
  // Live state for an in-progress barred_swap_chance decision. Cleared at
  // announcement -> campaign like other per-round executive-decision fields.
  swapWindow?: SwapWindow
  // Computed fields for efficient lookups
  adminPlayerId?: string // ID of the player with isAdmin = true
  currentBarredPlayerIds?: string[] // IDs of players barred in current round
  phase?: PhaseTypes // Player-facing phase derived from status (computed, not stored)
}

export interface GameStore {
  [id: string]: Game
}

export interface PlayerProjection {
  code: string
  status: StatusTypes
  phase?: PhaseTypes // Player-facing phase for display
  contentKey: StatusTypes
  session: {
    playerId: string
    playerName: string
  }
  actions: {
    canVote: boolean
    canDecide: boolean
    canResolveSwap: boolean
  }
  vote?: {
    hasSubmitted: boolean
    requiredVotes: number
    candidates: Array<{
      id: string
      name: string
    }>
  }
  decision?: {
    candidates: Array<{
      id: string
      name: string
    }>
    // Currently-barred players (from prior rounds), needed client-side to determine
    // eligibility of requalify_code / barred_swap_chance and, for the latter, as the
    // leader's target list. Never includes the player being barred this round (that bar
    // hasn't been confirmed/broadcast yet at decision-submit time).
    barredCandidates: Array<{
      id: string
      name: string
    }>
  }
  // Present only for the specific player who owns an unredeemed immunity_code /
  // requalify_code, and only during the campaign phase it's valid for. Never sent to the
  // host or to any other player.
  activeCode?: {
    code: string
    type: ActiveCodeType
  }
  // Present only for the specific barred player currently holding an active
  // barred_swap_chance window. Never sent to the host or to any other player.
  swapWindow?: {
    deadline: number
    candidates: Array<{
      id: string
      name: string
    }>
  }
  admin?: {
    canStartGame: boolean
    startBlockedReason?: string
    connectedPlayers: number
    minPlayersRequired: number
  }
}
