import type { NextApiRequest, NextApiResponse } from 'next'
import { emitRoleBasedGameUpdates, findGameByCode, persistGame } from '../../../../server/gameStore'
import type { Server as SocketIOServer } from 'socket.io'
import type { Server as NetServer, Socket } from 'net'

interface SocketServer extends NetServer {
  io?: SocketIOServer
}

interface SocketWithIO extends Socket {
  server: SocketServer
}

interface NextApiResponseWithSocket extends NextApiResponse {
  socket: SocketWithIO
}

interface RedeemCodeSubmission {
  playerId: string
  code: string
}

// Redeems an active immunity_code / requalify_code (see ActiveRoundCode in types/types.ts)
// generated by the leader's executive decision. Only redeemable during the campaign phase
// it was generated for, and never by the leader who generated it.
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    res.status(405).end()
    return
  }

  const { code } = req.query
  const { playerId, code: submittedCode } = req.body as RedeemCodeSubmission

  if (!playerId || !submittedCode) {
    return res.status(400).json({ error: 'Missing playerId or code' })
  }

  const game = await findGameByCode(code as string)
  if (!game) {
    return res.status(404).json({ error: 'Game not found' })
  }

  if (game.status !== 'campaign') {
    return res.status(400).json({ error: 'Codes can only be redeemed during the campaign phase' })
  }

  if (!game.activeCode || game.activeCode.validForRound !== game.currentRound) {
    return res.status(400).json({ error: 'There is no active code this cycle' })
  }

  const player = game.players.find(p => p.id === playerId)
  if (!player) {
    return res.status(404).json({ error: 'Player not found' })
  }

  if (player.id === game.activeCode.ownerId) {
    return res.status(403).json({ error: 'You cannot redeem your own code' })
  }

  const normalized = submittedCode.trim().toUpperCase()
  if (normalized !== game.activeCode.code) {
    return res.status(400).json({ error: 'Incorrect code' })
  }

  const codeType = game.activeCode.type
  let message: string
  let consumeCode = true

  if (codeType === 'immunity') {
    // NOTE: unlike a decision-time grant, this code is only redeemable once currentRound
    // has already advanced to activeCode.validForRound (checked above) — i.e. we are
    // already IN the cycle whose decision phase this should protect against, so no further
    // +1 here (decision.ts compares immuneFromBarInRound === game.currentRound at that
    // later point, when currentRound is still unchanged from right now).
    player.immuneFromBarInRound = game.currentRound
    message = 'You have been granted immunity from being barred this cycle.'
  } else {
    // requalify: no-op (but NOT consumed, so an actually-barred player can still use it
    // later this cycle) if the redeemer is already qualified.
    if (!player.isQualified) {
      player.isQualified = true
      message = 'You are qualified again!'
    } else {
      message = 'You are already qualified — this code has no effect for you.'
      consumeCode = false
    }
  }

  if (consumeCode) {
    delete game.activeCode
  }

  const resWithSocket = res as NextApiResponseWithSocket
  if (resWithSocket.socket?.server?.io) {
    emitRoleBasedGameUpdates(resWithSocket.socket.server.io, game)
  }

  await persistGame(game)

  res.status(200).json({ success: true, type: codeType, message })
}
